#!/bin/sh
#
# chkconfig: 2345 55 25
# Description: php-fpm init.d script, put in /etc/init.d, chmod +x /etc/init.d/php-fpm
#              For Debian, run: update-rc.d -f php-fpm defaults
#              For CentOS, run: chkconfig --add php-fpm
#
### BEGIN INIT INFO
# Provides:          php-fpm
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: php-fpm init.d script
# Description:       PHP FastCGI Process Manager
### END INIT INFO
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="PHP-FPM Daemon"
NAME=php-fpm
PREFIX=/usr/local/
DAEMON=$PREFIX/sbin/$NAME
CONF=/usr/local/etc/php/current/$NAME.conf
PID=/var/run/$NAME.pid
SCRIPT_DIR=$(cd "$(dirname ${BASH_SOURCE[0]})"; pwd)
SCRIPT=$SCRIPT_DIR/$NAME
if [ ! -x "$DAEMON" ] || [ ! -f "$CONF" ]; then
    echo -e "\033[33m $DAEMON has no permission to run. \033[0m"
    echo -e "\033[33m Or $CONF doesn't exist. \033[0m"
    sleep 1
    exit 1
fi

do_start() {
    if [ -f $PID ]; then
        echo -e "\033[33m $PID already exists. \033[0m"
        echo -e "\033[33m $DESC is already running or crashed. \033[0m"
    else
        echo -e "\033[32m $DESC Starting $CONF ... \033[0m"
        $DAEMON -g $PID -D -y $CONF
        sleep 1
        echo -e "\033[36m $DESC started. \033[0m"
    fi
}

do_stop() {
    if [ ! -f $PID ]; then
        echo -e "\033[33m $PID doesn't exist. \033[0m"
        echo -e "\033[33m $DESC isn't running. \033[0m"
    else
        echo -e "\033[32m $DESC Stopping $CONF ... \033[0m"
        kill `cat $PID`
        sleep 1
        echo -e "\033[36m $DESC stopped. \033[0m"
    fi
}

do_status() {
    if [ ! -f $PID ]; then
        echo -e "\033[33m $DESC isn't running. \033[0m"
    else
        ps cax | grep $NAME > /dev/null
        if [ $? -eq 0 ]; then
            echo -e "\033[36m $DESC is running. \033[0m"
        else
            echo -e "\033[33m $DESC isn't running. \033[0m"
        fi
    fi
}

do_reload() {
    if [ ! -f $PID ]; then
        do_start
    else
        echo -e "\033[32m $DESC Reloading $CONF ... \033[0m"
        if ! $DAEMON -t -y $CONF ; then
            echo -e "\033[33m $DESC could not reload due to configuration syntax error\033[0m"
        else
            kill `cat $PID`
            sleep 1
            $DAEMON -g $PID -D -y $CONF
            sleep 1
            echo -e "\033[36m $DESC reloaded. \033[0m"
        fi
    fi
}

do_test() {
    echo -e "\033[32m $DESC Testing $CONF ... \033[0m"
    $DAEMON -t -y $CONF
}

do_info() {
    $DAEMON -i
}

case "$1" in
 start)
 do_start
 ;;
 stop)
 do_stop
 ;;
 status)
 do_status
 ;;
 reload)
 do_reload
 ;;
 restart)
 do_stop
 do_start
 ;;
 test)
 do_test
 ;;
 info)
 do_info
 ;;
 *)
 echo "Usage: $SCRIPT {start|stop|status|reload|restart|test|info}"
 exit 2
 ;;
esac

exit 0
