#!/usr/bin/env bash

export NCREATE_MYSQL_USER="root"
export NCREATE_MYSQL_PASSWORD="root"

export OPEN_SUBLIME_TEXT="TRUE"
export GLOBAL_WWW_PATH="/var/www"

export NCREATE_SCRIPT_PATH="PATH/TO/create_nginx_osx"

export NGINX_VHOST_PATH="/etc/nginx/sites-enabled"
export PHP_FPM_POOL_PATH="/etc/php-fpm.d"

export NGINX_DEFAULT_USER="nginx"
export NGINX_DEFAULT_GROUP="nginx"

export DEFAULT_ADMIN_GROUP="adm"

# Where to soft link post receive script
export POST_RECEIVE_SCRIPT_PATH=""

alias wpcreate="$NCREATE_SCRIPT_PATH/wpcreate.sh"
alias laravelcreate="$NCREATE_SCRIPT_PATH/newLaravel.sh"
alias newSite="$NCREATE_SCRIPT_PATH/newSite.sh"
alias nConfigCreate="$NCREATE_SCRIPT_PATH/nginx_config_create.sh"
alias ncreate="$NCREATE_SCRIPT_PATH/ncreate.sh"

alias ndeploy="sudo $NCREATE_SCRIPT_PATH/deploy.sh"
alias ndelete="sudo $NCREATE_SCRIPT_PATH/ndelete.sh"

# Load artisan autocomplete
source "$NCREATE_SCRIPT_PATH/assets/bash_artisan"
